// Content actions types
export const FETCH_CONTENT_REQUEST = 'content/FETCH_CONTENT_REQUEST';
export const FETCH_CONTENT_SUCCESS = 'content/FETCH_CONTENT_SUCCESS';
export const FETCH_CONTENT_FAILURE = 'content/FETCH_CONTENT_FAILURE';

export const RESET_CONTENT = 'content/RESET_CONTENT';

// Folder action types
export const FETCH_ROOT_FOLDER_ID_REQUEST =
  'content/FETCH_ROOT_FOLDER_ID_REQUEST';
export const FETCH_ROOT_FOLDER_ID_SUCCESS =
  'content/FETCH_ROOT_FOLDER_ID_SUCCESS';
export const FETCH_ROOT_FOLDER_ID_FAILURE =
  'content/FETCH_ROOT_FOLDER_ID_FAILURE';

export const SET_CURRENT_FOLDER = 'content/SET_CURRENT_FOLDER';

export const FETCH_ALL_FOLDERS_REQUEST = 'content/FETCH_ALL_FOLDERS_REQUEST';
export const FETCH_ALL_FOLDERS_SUCCESS = 'content/FETCH_ALL_FOLDERS_SUCCESS';
export const FETCH_ALL_FOLDERS_FAILURE = 'content/FETCH_ALL_FOLDERS_FAILURE';

export const CREATE_FOLDER_REQUEST = 'content/CREATE_FOLDER_REQUEST';
export const CREATE_FOLDER_SUCCESS = 'content/CREATE_FOLDER_SUCCESS';
export const CREATE_FOLDER_FAILURE = 'content/CREATE_FOLDER_FAILURE';

export const UPDATE_FOLDER_REQUEST = 'content/UPDATE_FOLDER_REQUEST';
export const UPDATE_FOLDER_SUCCESS = 'content/UPDATE_FOLDER_SUCCESS';
export const UPDATE_FOLDER_FAILURE = 'content/UPDATE_FOLDER_FAILURE';

export const DELETE_FOLDER_REQUEST = 'content/DELETE_FOLDER_REQUEST';
export const DELETE_FOLDER_SUCCESS = 'content/DELETE_FOLDER_SUCCESS';
export const DELETE_FOLDER_FAILURE = 'content/DELETE_FOLDER_FAILURE';

// Url action types
export const FETCH_ALL_URL_REQUEST = 'content/FETCH_ALL_URL_REQUEST';
export const FETCH_ALL_URL_SUCCESS = 'content/FETCH_ALL_URL_SUCCESS';
export const FETCH_ALL_URL_FAILURE = 'content/FETCH_ALL_URL_FAILURE';

export const CREATE_URL_REQUEST = 'content/CREATE_URL_REQUEST';
export const CREATE_URL_SUCCESS = 'content/CREATE_URL_SUCCESS';
export const CREATE_URL_FAILURE = 'content/CREATE_URL_FAILURE';

export const UPDATE_URL_REQUEST = 'content/UPDATE_URL_REQUEST';
export const UPDATE_URL_SUCCESS = 'content/UPDATE_URL_SUCCESS';
export const UPDATE_URL_FAILURE = 'content/UPDATE_URL_FAILURE';

export const DELETE_URL_REQUEST = 'content/DELETE_URL_REQUEST';
export const DELETE_URL_SUCCESS = 'content/DELETE_URL_SUCCESS';
export const DELETE_URL_FAILURE = 'content/DELETE_URL_FAILURE';

export const contentActionTypes = {
  FETCH_CONTENT_REQUEST,
  FETCH_CONTENT_SUCCESS,
  FETCH_CONTENT_FAILURE,
  FETCH_ROOT_FOLDER_ID_REQUEST,
  FETCH_ROOT_FOLDER_ID_SUCCESS,
  FETCH_ROOT_FOLDER_ID_FAILURE,
  RESET_CONTENT,
  SET_CURRENT_FOLDER,
  FETCH_ALL_FOLDERS_REQUEST,
  FETCH_ALL_FOLDERS_SUCCESS,
  FETCH_ALL_FOLDERS_FAILURE,
  CREATE_FOLDER_REQUEST,
  CREATE_FOLDER_SUCCESS,
  CREATE_FOLDER_FAILURE,
  UPDATE_FOLDER_REQUEST,
  UPDATE_FOLDER_SUCCESS,
  UPDATE_FOLDER_FAILURE,
  DELETE_FOLDER_REQUEST,
  DELETE_FOLDER_SUCCESS,
  DELETE_FOLDER_FAILURE,
  FETCH_ALL_URL_REQUEST,
  FETCH_ALL_URL_SUCCESS,
  FETCH_ALL_URL_FAILURE,
  CREATE_URL_REQUEST,
  CREATE_URL_SUCCESS,
  CREATE_URL_FAILURE,
  UPDATE_URL_REQUEST,
  UPDATE_URL_SUCCESS,
  UPDATE_URL_FAILURE,
  DELETE_URL_REQUEST,
  DELETE_URL_SUCCESS,
  DELETE_URL_FAILURE
};
