export const SET_USER = "auth/SET_USER";

export const FETCH_USER_REQUEST = "auth/FETCH_USER_REQUEST";
export const FETCH_USER_SUCCESS = "auth/FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE = "auth/FETCH_USER_FAILURE";

export const LOGIN_REQUEST = "auth/LOGIN_REQUEST";
export const LOGIN_SUCCESS = "auth/LOGIN_SUCCESS";
export const LOGIN_FAILURE = "auth/LOGIN_FAILURE";

export const REGISTER_REQUEST = "auth/REGISTER_REQUEST";
export const REGISTER_SUCCESS = "auth/REGISTER_SUCCESS";
export const REGISTER_FAILURE = "auth/REGISTER_FAILURE";

export const UPDATE_USER_REQUEST = "auth/UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "auth/UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILURE = "auth/UPDATE_USER_FAILURE";

export const DELETE_USER_REQUEST = "auth/DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "auth/DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "auth/DELETE_USER_FAILURE";

export const LOGOUT_REQUEST = "auth/LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "auth/LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "auth/LOGOUT_FAILURE";

export const authActionTypes = {
  SET_USER,
  FETCH_USER_REQUEST,
  FETCH_USER_SUCCESS,
  FETCH_USER_FAILURE,
  LOGIN_REQUEST,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  REGISTER_REQUEST,
  REGISTER_SUCCESS,
  REGISTER_FAILURE,
  UPDATE_USER_REQUEST,
  UPDATE_USER_SUCCESS,
  UPDATE_USER_FAILURE,
  DELETE_USER_REQUEST,
  DELETE_USER_SUCCESS,
  DELETE_USER_FAILURE,
  LOGOUT_REQUEST,
  LOGOUT_SUCCESS,
  LOGOUT_FAILURE
};
