export const SET_MODAL_CONTENT = 'modal/SET_MODAL_CONTENT';

export const CREATE_FOLDER_MODAL_TOGGLE = 'modal/CREATE_FOLDER_MODAL_TOGGLE';
export const CREATE_URL_MODAL_TOGGLE = 'modal/CREATE_URL_MODAL_TOGGLE';
export const UPDATE_URL_MODAL_TOOGGLE = 'modal/UPDATE_URL_MODAL_TOOGGLE';

export const modalActionTypes = {
  SET_MODAL_CONTENT,
  CREATE_FOLDER_MODAL_TOGGLE,
  CREATE_URL_MODAL_TOGGLE,
  UPDATE_URL_MODAL_TOOGGLE
};
